[package]
name = "monomana"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
anyhow = "1.0"
walkdir = "2.4"
dirs = "5.0"
log = "0.4"
env_logger = "0.11"

[dev-dependencies]
tempfile = "3.8"
